stages:
  train:
    cmd: python3 -m deepview.modelpack.trainer --load=params.yaml --dataset=dataset.yaml
      --dvclive=out --report=md
    params:
    - params.yaml:
    metrics:
    - out/metrics.json
    deps:
    - dataset
    - dataset.yaml
    - Pipfile.lock
    outs:
    - out/config.json
    - out/labels.txt
    - out/last.h5
    - out/best.h5
    - out/report.md
params:
- out/params.yaml
metrics:
- out/metrics.json
plots:
- out/plots/metrics:
    x: step
