stages:
  manifest:
    cmd: make manifest
    deps:
    - Makefile
    outs:
    - dvclive/modelpack.json
    - dvclive/converter.json
  train:
    cmd: make train
    params:
    - params.yaml:
    metrics:
    - dvclive/metrics.json 
    deps:
    - dvclive/modelpack.json
    - dvclive/converter.json
    - Makefile
    - dataset
    - dataset.yaml
    outs:
    - out/config.json
    - out/labels.txt
    - out/last.h5
    - out/best.h5
    - dvclive/static
    - dvclive/report.md
  deploy:
    cmd: make deploy
    params:
    - params.yaml:
    deps:
    - dvclive/converter.json
    - Makefile
    - dataset
    - out/labels.txt
    - out/last.h5
    - out/best.h5
    outs:
    - out/last.rtm
    - out/best.rtm
