stages:
  train:
    cmd: python3 -m deepview.modelpack.trainer --load=params.yaml --dataset=dataset.yaml --dvclive=out
    params:
    - params.yaml:
    metrics:
    - out/metrics.json
    deps:
    - dataset
    - dataset.yaml
    outs:
    - out/config.json
    - out/labels.txt
    - out/last.h5
    - out/best.h5