stages:
  train:
    cmd: make train
    params:
    - params.yaml
    deps:
    - Makefile
    - dataset
    - dataset.yaml
    outs:
    - out/best.h5
    - out/labels.txt
    - out/last.h5
    - out/summary.csv
