name: Manual

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: mltrain
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.8
          miniforge-version: latest
          mamba-version: latest
          use-mamba: true
          auto-update-conda: true
          channels: conda-forge
          activate-environment: playingcards
          environment-file: conda.list
      - name: PyPi Packages
        run: pip install -r requirements.txt
      - name: dvc pull
        run: dvc pull
      - name: dvc push
        run: dvc push -r private
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Synchronizing DVC from GitHub Action
          file_pattern: 'dvc.lock'
      - run: |
          cp out/best.h5 out/playingcards.h5
          cp out/best.rtm out/playingcards.rtm
      - name: publish report
        run: |
          aws s3 cp out/report.md s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}/report.md
          aws s3 cp --recursive out/static s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}/static
          sed ':l s/\(([^ )]*\)[ ]/\1%20/;tl' out/report.md | \
          sed 's,(static/,(https://datasets.deepviewml.com/${{ github.event.repository.name }}/reports/${{ github.sha }}/static/,' > report.md
          cat report.md > $GITHUB_STEP_SUMMARY