name: Pull Request

on: pull_request

jobs:
    train:
        runs-on: mltrain
        env:
            HOSTID: ${{ secrets.MODELPACK_HOSTID }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        steps:
        - uses: actions/checkout@v3
        - name: modelpack license
          uses: mobiledevops/secret-to-file-action@v1
          with:
            base64-encoded-secret: ${{ secrets.MODELPACK_LICENSE }}
            filename: "modelpack.lic"
        - name: dvc pull
          run: dvc pull
        - name: dvc repro
          run: dvc repro
        - name: dvc push
          run: dvc push -r private
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Synchronizing DVC from GitHub Action
            file_pattern: 'dvc.lock'
        - name: publish report
          run: |
            aws s3 cp dvclive/report.md s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}
            aws s3 cp --recursive dvclive/static s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}/static
            sed 's,!\[static/,!\[https://datasets.deepviewml.com/${{ github.event.repository.name }}/reports/${{ github.sha }}/static/,' dvclive/report.md > $GITHUB_STEP_SUMMARY
