name: Pull Request

on: pull_request

jobs:
  train:
    runs-on: mltrain
    env:
      HOSTID: ${{ secrets.MODELPACK_HOSTID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pipenv'
    - name: Python Version
      run: python --version
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - run: pipenv install
    - run: pipenv run python --version
    - name: Python Packages
      run: pipenv run pip freeze
    - name: Environment Variables
      run: env
    - name: dvc pull
      run: pipenv run dvc pull
    - name: dvc repro
      run: pipenv run dvc repro
    - name: dvc push
      run: pipenv run dvc push -r private
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Synchronizing DVC from GitHub Action
        file_pattern: 'dvc.lock'
    - name: publish report
      run: |
        aws s3 cp out/report.md s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}/report.md
        aws s3 cp --recursive out/static s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}/static
        sed ':l s/\(([^ )]*\)[ ]/\1%20/;tl' out/report.md | \
        sed 's,(static/,(https://datasets.deepviewml.com/${{ github.event.repository.name }}/reports/${{ github.sha }}/static/,' > report.md
        cat report.md > $GITHUB_STEP_SUMMARY
    - name: debug report
      run: |
        ls report.md
        cat report.md
    - uses: mshick/add-pr-comment@v2
      with:
        message-path: |
          report.md
        message-id: 'dvc-report'
        refresh-message-position: true