name: Pull Request

on: pull_request

jobs:
  train:
    runs-on: mltrain
    defaults:
      run:
        shell: bash -el {0}
    env:
      HOSTID: ${{ secrets.MODELPACK_HOSTID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        mamba-version: 1.5.7
        use-mamba: true
        auto-update-conda: false
        channels: conda-forge
        activate-environment: playingcards
        environment-file: conda.list
    - run: |
        mamba info
        mamba list
        pip install -r requirements.txt
        dvc pull
        dvc repro
        sed -i 's/params.yaml/## Parameters/g; s/metrics.json/## Training Metrics/g' out/report.md
        printf '\n## Validation Metrics\n' >> out/report.md
        dvc metrics show --md out/best.h5.metrics.json out/best.rtm.metrics.json | sed 's,out/,,g; s,.metrics.json,,g' >> out/report.md
        dvc push -r private
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Synchronizing DVC from GitHub Action
        file_pattern: 'dvc.lock'
    - name: publish report
      run: |
        aws s3 cp out/report.md s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}/report.md
        aws s3 cp --recursive out/static s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}/static
        sed ':l s/\(([^ )]*\)[ ]/\1%20/;tl' out/report.md | \
        sed 's,(static/,(https://datasets.deepviewml.com/${{ github.event.repository.name }}/reports/${{ github.sha }}/static/,' > report.md
        cat report.md > $GITHUB_STEP_SUMMARY
    - name: debug report
      run: |
        ls report.md
        cat report.md
    - uses: mshick/add-pr-comment@v2
      with:
        message-path: |
          report.md
        message-id: 'dvc-report'
        refresh-message-position: true
