name: Release

on:
  push:
    tags:
    - "v*.*"

jobs:
  release:
    runs-on: mltrain
    defaults:
      run:
        shell: bash -el {0}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          mamba-version: 1.5.7
          use-mamba: true
          auto-update-conda: true
          channels: conda-forge
          activate-environment: playingcards
          environment-file: conda.lock
      - run: |
          mamba info
          mamba list
          pip install -r requirements.txt
          dvc pull
          dvc repro
      - run: |
          cp out/best.h5 out/playingcards.h5
          cp out/best.rtm out/playingcards.rtm
      - name: report
        run: |
          aws s3 cp out/report.md s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}/report.md
          aws s3 cp --recursive out/static s3://deepviewml-datasets/${{ github.event.repository.name }}/reports/${{ github.sha }}/static
          sed ':l s/\(([^ )]*\)[ ]/\1%20/;tl' out/report.md | \
          sed 's,(static/,(https://datasets.deepviewml.com/${{ github.event.repository.name }}/reports/${{ github.sha }}/static/,' > report.md
          cat report.md > $GITHUB_STEP_SUMMARY
      - uses: softprops/action-gh-release@v1
        with:
          body_path: report.md
          files: |
            out/playingcards.h5
            out/playingcards.rtm
